In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df = pd.DataFrame({
    'men': [80.2, 80.8, 57.5, 98, 50.5, 73.8, 77.4, 59.7, 77.9, 52.6],
    'women': [57.9, 57.3, 72.8, 48.2, 59.5, 48.3, 61.2, 53.9, 53.9, 70.7]
})

## Задание 1.5.1

Задача с использованием Python
С помощью Python мы можем найти среднее значение списка, просто используя функцию mean(). Единственный аргумент этой функции — список данных, на котором необходимо посчитать значение.

В таблице выше представлен ряд данных о весе 20 случайно выбранных клиентов медицинской клиники — 10 мужчин и 10 женщин (в кг). Скопируйте датафрейм, который описывают нашу таблицу, в свой ноутбук и выполните задание.

Средний вес мужчины в данной выборке превышает средний вес женщины на ______ кг.

Введите значение, округлив до 1 знака после точки-разделителя.

In [81]:

print("Средний вес мужчины в данной выборке превышает средний вес женщины на {:0.1f} кг".
      format(df.men.mean() - df.women.mean()))

Средний вес мужчины в данной выборке превышает средний вес женщины на 12.5 кг


## Задание 1.5.2

Дано два набора данных: 2,7,4,3,6,4,1,2 и 5,2,4,8,1,6,7 
Медиана в первом наборе данных равна _____. (введите значение с точкой в качестве разделителя)

In [82]:
m1 = np.median([2,7,4,3,6,4,1,2])
m2 = np.median([5,2,4,8,1,6,7])
print ("Медиана в первом наборе данных равна {:0.1f}".format(m1))
print ("Это на {:0.1f} меньше медианы во втором наборе данных.".format(m2-m1))

Медиана в первом наборе данных равна 3.5
Это на 1.5 меньше медианы во втором наборе данных.


## Задание 1.5.3
Следуя описанному в теоретической части алгоритму, мы можем написать вычисление медианы в Python по аналогии со средним арифметическим. Для этого нам понадобится функция median().

Используя median(), найдем медиану списка данных, применив функцию ко всему датафрейму или по отдельности для каждой серии.

Вспоминаем выборку из 20 пациентов.

In [83]:
df = pd.DataFrame({
    'men': [80.2, 80.8, 57.5, 98, 50.5, 73.8, 77.4, 59.7, 77.9, 52.6],
    'women': [57.9, 57.3, 72.8, 48.2, 59.5, 48.3, 61.2, 53.9, 53.9, 70.7]
})

Медианный вес среди мужчин (введите значение с точкой в качестве разделителя):

In [84]:
df.men.median()

75.6

Медианный вес среди женщин (введите значение с точкой в качестве разделителя):

In [85]:
round(df.women.median(),1)

57.6

In [86]:
df
dff = np.vstack((df.men, df.women)).flatten()
np.median(dff)


59.6

# 1.6. Квартили

## Задание 1.6.1
Возьмём два знакомых нам по третьей задаче набора данных:


In [87]:
m1 = [2,7,4,3,6,4,1,2]
m2 = [5,2,4,8,1,6,7]
display(np.sort(m1),np.sort(m2))


array([1, 2, 2, 3, 4, 4, 6, 7])

array([1, 2, 4, 5, 6, 7, 8])

In [88]:
np.quantile(m1, q = [0.3, 0.7])


array([2.1, 4. ])

In [89]:
np.quantile(m2, q = [0.25, 0.75])

array([3. , 6.5])

Ответ
Верно:Упорядочим значения в первом наборе данных: 1, 2, 2, 3, 4, 4, 6, 7. Медиана находится между 3 и 4.
Значит, нижняя половина данных: 1, 2, 2, 3 , и верхняя половина данных: 4, 4, 6, 7 .
В каждой половине n=4 наблюдений, значит нижний и верхний квартиль находятся между 2 и 3
наблюдениями в нижней и верхней части данных, соответственно.
Вторая выборка записана по возрастанию: 1, 2, 4, 5, 6, 7, 8 .
Медиана равна 5 и делит данные на 2 части: 1, 2, 4 и 6, 7, 8 . В каждой части n=3 наблюдений,
 значит нижний и верхний квартиль равны второму наблюдению в нижней и верхней части данных
 соответственно.

# ВЫЧИСЛЯЕМ КВАРТИЛИ В PYTHON

Для вычисления квартилей в pandas используется функция quantile(). Она возвращает значение в заданном квартиле. Значение квартиля задается в диапазоне от [0,...1]. Например, для нижнего квартиля это значение равно , для верхнего — .

Также у quantile()  существует необязательный параметр, который  указывает метод интерполяции, который нужно использовать, когда требуемый квантиль лежит между двумя точками данных. По умолчанию используется линейная интерполяция.
#### DataFrame.quantile(q=0.5, axis=0, numeric_only=True, interpolation='linear')




Чтобы вычислять квантиль как среднее между двумя точками в части данных, необходимо сменить вид интерполяции на следующий:
#### DataFrame.quantile(q=0.5, axis=0, numeric_only=True, interpolation='midpoint')

In [90]:
df = pd.DataFrame({
    'men': [80, 80.8, 57.5, 98, 50.5, 73.8, 77.4, 59.7, 77.9, 52.6],
    'women': [57.9, 57.3, 72.8, 48.2, 59.5, 48.3, 61.2, 53.9, 53.9, 70.7]
})


## Задание 1.7.1
5 points possible (graded)
Найдите Q1 и Q3 для мужчин и женщин, используя Python (выпишите результат, округляя до 1 знака после точки-разделителя):

Для того, чтобы округлить до 1 знака после точки-разделителя, используйте round(value, 1), где value — это число для округления.


In [91]:
q_m = round(df.men.quantile(q = [0.25, 0.75], interpolation='midpoint'),1)
q_w = round(df.women.quantile(q = [0.25, 0.75], interpolation='midpoint'),1)
print(q_m, q_w )

0.25    58.6
0.75    79.0
Name: men, dtype: float64 0.25    53.9
0.75    60.4
Name: women, dtype: float64


# 1.8. Меры разброса
## Задание 1.9.1
Найдите размах и межквартильный размах для веса на выборке пациентов клиники.
Для удобства вычисления размаха можете использовать стандартные функции min(), max() для серий в pandas.
Также используйте знания о функции quantile() для вычисления межквартильного размаха.
Используйте ранее приведенный параметр интерполяции для вычислени квартилей в pandas.


In [92]:
import pandas as pd
df = pd.DataFrame({
    'men': [80.2, 80.8, 57.5, 98, 50.5, 73.8, 77.4, 59.7, 77.9, 52.6],
    'women': [57.9, 57.3, 72.8, 48.2, 59.5, 48.3, 61.2, 53.9, 53.9, 70.7]
})

In [108]:
x_m = df.men.max() - df.men.min() #размах выборки по весу мужчин
x_w = df.women.max() -df.women.min() #размах выборки по весу женщин

IQR_M = df.men.quantile(q = 0.75, interpolation='midpoint') - df.men.quantile(q = 0.25, interpolation='midpoint')
IQR_W = df.women.quantile(q = 0.75, interpolation='midpoint') - df.women.quantile(q = 0.25, interpolation='midpoint')

print(round(x_m,1),round(IQR_M,1))
print(round(x_w,1),round(IQR_W,1))

47.5 20.5
24.6 6.5


## Задание 1.9.2

Вычисляем стандартное отклонение в Python
Для вычисления стандартного отклонения в выборке в Python используется функция std().
Единственным аргументом функции является диапазон данных. В данном случае диапазоном данных может выступать как серия pandas,
так и весь датафрейм целиком. Aналогично для вычисления дисперсии используется функция var().

Задание: Найдите дисперсию и стандартное отклонение веса для выборки пациентов клиники.
Выпишите результат, округляя до 1 знака после точки-разделителя:


In [116]:
d_m = round(df.men.std(),1)
d_w = round(df.women.std(),1)
di_m = round(df.men.var(),1)
di_w = round(df.women.var(),1)
print("Стандартное отклонение веса для мужчин {:0.1f} кг".format(d_m))
print("Дисперсия по весу для мужчин {:0.1f}".format(di_m))
print("Стандартное отклонение веса для женщин {:0.1f} кг".format(d_w))
print("Дисперсия по весу для женщин {:0.1f}".format(di_w))

Стандартное отклонение веса для мужчин 15.2 кг
Дисперсия по весу для мужчин 230.5
Стандартное отклонение веса для женщин 8.3 кг
Дисперсия по весу для женщин 68.4
